import { useState } from 'react'
import { ArrowUpRight, Check, ChevronRight, MapPin, Menu, Phone, Star, X } from 'lucide-react'
import { business } from './data/business'
import './index.css'

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const closeMenu = () => setMenuOpen(false)

  return (
    <div className="site-shell">
      <header className="site-header">
        <a className="wordmark" href="#home" onClick={closeMenu}><span>President Limo</span><small>Australia</small></a>
        <nav className={menuOpen ? 'site-nav is-open' : 'site-nav'} aria-label="Primary navigation">
          {['Services', 'About', 'Experience', 'Reviews', 'Contact'].map((item) => <a key={item} href={`#${item.toLowerCase()}`} onClick={closeMenu}>{item}</a>)}
          <a className="button button-small" href="#contact" onClick={closeMenu}>Book a ride <ArrowUpRight size={15} /></a>
        </nav>
        <button className="menu-button" type="button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={21} /> : <Menu size={21} />}</button>
      </header>
      <main>
        <section className="hero section-pad" id="home"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-mark" /> Melbourne <span className="dot">•</span> Australia</p><h1>Arrive in<br /><em>comfort.</em><br />Travel in style.</h1><p className="hero-intro">Professional limousine transportation across Melbourne, Australia.</p><div className="hero-actions"><a className="button" href="#contact">Book a ride <ArrowUpRight size={16} /></a><a className="text-link" href={business.phoneHref}><Phone size={15} /> Call 1800 986 658</a></div></div><div className="hero-image-wrap"><img src="https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1400&q=88" alt="Black luxury limousine parked outside a building" /><div className="image-caption"><span>01</span><span>Professional transport<br />across Melbourne</span></div></div><div className="hero-foot"><span>Available 24 hours</span><span className="line" /><span>Est. Melbourne service</span></div></section>
        <section className="facts section-pad" aria-label="Quick facts"><div className="fact"><strong>24/7</strong><span>Available</span></div><div className="fact"><strong>{business.rating} / 5</strong><span>Google rating</span></div><div className="fact"><strong>{business.reviewCount}</strong><span>Google reviews</span></div><div className="fact"><strong>Melbourne</strong><span>Based</span></div></section>
        <section className="services section-pad" id="services"><div className="section-heading"><p className="eyebrow">Our service</p><h2>Professional transportation,<br /><em>presented simply.</em></h2></div><div className="service-list">{[['01', 'Luxury Transportation', 'Professional limousine transportation for your journey across Melbourne.'], ['02', '24/7 Availability', 'Available around the clock for your transportation needs.'], ['03', 'Comfort & Style', 'A comfortable and polished travel experience from pickup to destination.']].map(([number, title, body]) => <article className="service-row" key={number}><span className="service-number">{number}</span><div className="service-icon"><Check size={16} /></div><div><h3>{title}</h3><p>{body}</p></div><ChevronRight className="service-arrow" size={21} /></article>)}</div></section>
        <section className="about section-pad" id="about"><div className="about-image"><img src="https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1100&q=88" alt="Elegant black car on a Melbourne street" /><span className="vertical-label">PRESIDENT LIMO AUSTRALIA</span></div><div className="about-copy"><p className="eyebrow">About President Limo</p><h2>A professional way<br />to move through <em>Melbourne.</em></h2><p>President Limo Australia is a Melbourne-based limousine service with availability 24 hours a day.</p><address><MapPin size={17} /><span>2/430 Little Collins St<br />Melbourne VIC 3000<br />Australia</span></address><a className="text-link" href={business.mapsHref} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={15} /></a></div></section>
        <section className="experience section-pad" id="experience"><div className="experience-intro"><p className="eyebrow eyebrow-light">The experience</p><h2>Designed around<br /><em>your journey.</em></h2><p>Every detail kept clear, comfortable, and dependable from pickup to destination.</p></div><div className="experience-list">{[['01', '24/7 Availability'], ['02', 'Professional Service'], ['03', 'Melbourne Based']].map(([number, title]) => <div className="experience-row" key={number}><span>{number}</span><strong>{title}</strong><ArrowUpRight size={18} /></div>)}</div></section>
        <section className="feature-image"><img src="https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1800&q=88" alt="Luxury car driving through the city at dusk" /><div className="feature-overlay"><p className="eyebrow eyebrow-light">Travel in style</p><h2>Comfortable.<br />Professional.<br /><em>Straightforward.</em></h2><a className="button button-light" href="#contact">Book a ride <ArrowUpRight size={16} /></a></div></section>
        <section className="reviews section-pad" id="reviews"><div><p className="eyebrow">Customer reviews</p><h2>Trusted by the<br /><em>people we move.</em></h2></div><div className="rating-block"><div className="rating-number">{business.rating}<span>/ 5</span></div><div className="stars" aria-label={`${business.rating} out of 5 stars`}>{[1, 2, 3, 4, 5].map((star) => <Star key={star} size={17} fill="currentColor" />)}</div><p>Based on {business.reviewCount} Google reviews</p><a className="text-link" href="https://www.google.com/search?q=President+Limo+Australia+reviews" target="_blank" rel="noreferrer">View Google reviews <ArrowUpRight size={15} /></a></div></section>
        <section className="contact section-pad" id="contact"><div className="contact-copy"><p className="eyebrow eyebrow-light">Ready to ride?</p><h2>Make your next<br /><em>journey simple.</em></h2><a className="button button-light" href={business.phoneHref}><Phone size={16} /> Call now</a><a className="contact-phone" href={business.phoneHref}>{business.phone}</a></div><form className="enquiry-form" onSubmit={(event) => event.preventDefault()}><p className="eyebrow eyebrow-light">Send an enquiry</p><label>Name<input type="text" name="name" autoComplete="name" /></label><label>Phone<input type="tel" name="phone" autoComplete="tel" /></label><label>Email<input type="email" name="email" autoComplete="email" /></label><label>Message<textarea name="message" rows="3" /></label><button className="form-submit" type="submit">Send enquiry <ArrowUpRight size={16} /></button></form></section>
        <section className="contact-details section-pad"><div><p className="eyebrow">Find us</p><h2>President Limo<br /><em>Australia.</em></h2></div><div className="details-grid"><div><span>Address</span><a href={business.mapsHref} target="_blank" rel="noreferrer">2/430 Little Collins St<br />Melbourne VIC 3000<br />Australia</a></div><div><span>Phone</span><a href={business.phoneHref}>{business.phone}</a></div><div><span>Hours</span><p>{business.availability}</p></div></div></section>
      </main>
      <footer className="site-footer"><div className="footer-main"><div><a className="wordmark wordmark-light" href="#home"><span>President Limo</span><small>Australia</small></a><p>Premium Limousine Service<br />Melbourne, Australia</p></div><div className="footer-nav"><span>Navigation</span><a href="#home">Home</a><a href="#services">Services</a><a href="#about">About</a><a href="#reviews">Reviews</a><a href="#contact">Contact</a></div><div className="footer-contact"><span>Contact</span><a href={business.phoneHref}>{business.phone}</a><a href={business.mapsHref} target="_blank" rel="noreferrer">2/430 Little Collins St<br />Melbourne VIC 3000</a><p>{business.availability}</p></div></div><div className="footer-bottom"><span>© 2026 President Limo Australia</span><span>Website concept created by Aakash Neupane</span></div></footer>
      <a className="mobile-call" href={business.phoneHref} aria-label="Call President Limo Australia"><Phone size={18} /></a>
    </div>
  )
}

export default App
